version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://176.108.242.162:5433/keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - "8080:8080"

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    environment:
      KEYCLOAK_URL: http://keycloak:8080/
      REALM: myrealm
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8001:8000"
    depends_on:
      - keycloak

#  api_gateway:
#    build:
#      context: ./services/api_gateway
#      dockerfile: Dockerfile
#    environment:
#      AUTH_SERVICE_URL: http://auth:8000
#    ports:
#      - "8000:8000"
#    depends_on:
#      - auth

volumes:
  postgres_data:
