version: "3.9"

services:
  auth:
    image: registry.example.com/problemka/auth:dev
    env_file:
      - .env.dev
    ports:
      - "8001:8000"
    restart: always

  reports:
    image: registry.example.com/problemka/reports:dev
    env_file:
      - .env.dev
    ports:
      - "8002:8000"
    restart: always
